
name: CI

# Controls when the action will run. Triggers the workflow on repository dispatch
# events but only for the master branch
on:
  repository_dispatch:
    types: [machinelearningservices-modelregistered, machinelearningservices-modeldeployed, machinelearningservices-runcompleted, machinelearningservices-runstatuschanged, machinelearningservices-datasetdriftdetected, appconfiguration-keyvaluemodified, appconfiguration-keyvaluedeleted, storage-blobcreated, storage-blobdeleted, storage-blobrenamed, storage-directorycreated, storage-directoryrenamed, storage-directorydeleted, containerregistery-imagepushed, containerregistery-imagedeleted, containerregistery-chartpushed, containerregistery-chartdeleted, web/sites-backupoperationstarted, web/sites-backupoperationcompleted, web/sites-backupoperationfailed, web/sites-restoreoperationstarted, web/sites-restoreoperationcompleted, web/sites-restoreoperationfailed, web/sites-slotswapstarted, web/sites-slotswapcompleted, web/sites-slotswapfailed, web/sites-slotswapwithpreviewstarted, web/sites-slotswapwithpreviewcancelled, eventhub-capturefilecreated, devices-devicecreated, devices-devicedeleted, devices-deviceconnected, devices-devicedisconnected, devices-devicetelementry, keyvault-certificatenewversioncreated, keyvault-certificatenearexpiry, keyvault-certificateexpired, maps-geofenceentered, maps-geofenceexited, maps-geofenceresult, media-jobstatechange, media-jobscheduled, media-jobprocessing, media-jobcanceling, media-jobfinished, media-jobcanceled, media-joberrored, web/sites-appupdated-changedappsettings]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your  repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
