
name: CI

# Controls when the action will run. Triggers the workflow on repository dispatch
# events but only for the master branch
on:
  repository_dispatch:
    types: [customEvent]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your  repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
   
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }
